apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-microservice
  namespace: local-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-microservice
  template:
    metadata:
      labels:
        app: rag-microservice
    spec:
      containers:
        - name: rag-microservice
          image: your-dockerhub-username/rag-microservice:latest
          ports:
            - containerPort: 8002
          env:
            - name: OLLAMA_BASE_URL
              value: "http://ollama:11434"
---
apiVersion: v1
kind: Service
metadata:
  name: rag-microservice
  namespace: local-rag
spec:
  selector:
    app: rag-microservice
  ports:
    - port: 8002
      targetPort: 8002
